export const LOAD_SC_PROPS = "LOAD_SC_PROPS";
export const LOAD_USER_PROPS = "LOAD_USER_PROPS";
export const SET_APP_HANDLER_POSITIVE = "SET_APP_HANDLER_POSITIVE";
export const SET_APP_HANDLER_NEGATIVE = "SET_APP_HANDLER_NEGATIVE";
export const SET_SEND_INFORMATION = "SET_SEND_INFORMATION";
export const SET_RECEIVED_MESSAGES = "SET_RECEIVED_MESSAGES";
